CI-Plateform project/CI-Plateform/Controllers/TimeSheetController.cs
using CI_Plateform.DbModels;
using CI_Plateform.Models;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CI_Plateform.Controllers
{
    public class TimeSheetController : Controller
    {
        public ClPlatformContext _db = new ClPlatformContext();

        #region Timesheet
        public IActionResult Timesheet()
        {
            PlateformVM plateformVM = new PlateformVM();
            plateformVM.Missions = _db.Missions.ToList();
            plateformVM.Timesheets = _db.Timesheets.Where(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId"))).ToList();
            plateformVM.user = _db.Users.FirstOrDefault(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")));


            List<SelectListItem> list = new List<SelectListItem>();
            var temp = _db.MissionApplications.Where(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")) && x.DeletedAt == null && x.Mission.MissionType == 1).Select(x => x.MissionId).ToList();
            foreach (var item in temp)
            {
                var mission = _db.Missions.FirstOrDefault(x => x.MissionId == item);
                list.Add(new SelectListItem() { Text = mission.Title, Value = mission.MissionId.ToString() });
            }
            plateformVM.MissionHourList = list;

            List<SelectListItem> list1 = new List<SelectListItem>();
            var temp1 = _db.MissionApplications.Where(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")) && x.DeletedAt == null && x.Mission.MissionType == 2).Select(x => x.MissionId).ToList();
            foreach (var item in temp1)
            {
                var mission = _db.Missions.FirstOrDefault(x => x.MissionId == item);
                list1.Add(new SelectListItem() { Text = mission.Title, Value = mission.MissionId.ToString() });
            }
            plateformVM.MissionGoalList = list1;

            return View(plateformVM);
        }

        /*[HttpGet]
        public IActionResult timeHouradd()
        {
            PlateformVM plateformVM = new PlateformVM();

            List<SelectListItem> list = new List<SelectListItem>();
            var temp = _db.MissionApplications.Where(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")) && x.DeletedAt == null && x.Mission.MissionType == 1).Select(x => x.MissionId).ToList();
            foreach (var item in temp)
            {
                var mission = _db.Missions.FirstOrDefault(x => x.MissionId == item);
                list.Add(new SelectListItem() { Text = mission.Title, Value = mission.MissionId.ToString() });
            }
            plateformVM.MissionHourList = list;
            return View(plateformVM);
        }*/

        [HttpPost] 
        public IActionResult timeHouradd(PlateformVM model)
        {
            if (model.timesheet != null)
            {
                model.timesheet.UserId = int.Parse(HttpContext.Session.GetString("UserId"));
                model.timesheet.MissionId = model.mission.MissionId;
                model.timesheet.CreatedAt = DateTime.Now;
                _db.Timesheets.Add(model.timesheet);
                _db.SaveChanges();
                return RedirectToAction("Timesheet", "Timesheet");
            }
            else
                return NotFound();
        }
        [HttpGet]
        public IActionResult TimeHourEdit(int? id)
        {
            PlateformVM plateformVM = new PlateformVM();
            plateformVM.timesheet = _db.Timesheets.FirstOrDefault(x => x.TimesheetId == id);
            

            List<SelectListItem> list = new List<SelectListItem>();
            var temp = _db.MissionApplications.Where(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")) && x.DeletedAt == null && x.Mission.MissionType == 1).Select(x => x.MissionId).ToList();
            foreach (var item in temp)
            {
                var mission = _db.Missions.FirstOrDefault(x => x.MissionId == item);
                list.Add(new SelectListItem() { Text = mission.Title, Value = mission.MissionId.ToString() });
            } 
            plateformVM.MissionHourList = list;
            return View(plateformVM);
        }
        [HttpPost]
        public IActionResult TimeHourEdit(PlateformVM model)
        {
            if (model.timesheet != null)
            {
                model.timesheet.UserId = int.Parse(HttpContext.Session.GetString("UserId"));

                model.timesheet.MissionId = model.mission.MissionId;

                model.timesheet.UpdatedAt = DateTime.Now;
                if(model.timesheet.Time != null) {
                _db.Timesheets.Update(model.timesheet);
                _db.SaveChanges();
                }
                else
                {
                    return NotFound();
                }
                return RedirectToAction("Timesheet", "Timesheet");
            }
            else
                return NotFound();
        }
        public IActionResult timeHourDelete(int? id)
        {
            var timesheet = _db.Timesheets.FirstOrDefault(x => x.TimesheetId == id);
            if (timesheet == null)
            {
                return NotFound();
            }
            timesheet.DeletedAt = DateTime.Now;
            _db.Timesheets.Remove(timesheet);
            _db.SaveChanges();
            return RedirectToAction("Timesheet", "Timesheet");
        }

        /*[HttpGet]
       public IActionResult timeGoaladd()
       {
           PlateformVM plateformVM = new PlateformVM();
           List<SelectListItem> list = new List<SelectListItem>();
           var temp = _db.MissionApplications.Where(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")) && x.DeletedAt == null && x.Mission.MissionType == 2).Select(x => x.MissionId).ToList();
           foreach (var item in temp)
           {
               var mission = _db.Missions.FirstOrDefault(x => x.MissionId == item);
               list.Add(new SelectListItem() { Text = mission.Title, Value = mission.MissionId.ToString() });
           }
           plateformVM.MissionList = list;
           return View(plateformVM);
       }*/

        [HttpPost]
        public IActionResult timeGoaladd(PlateformVM model)
        {
            if (model.timesheet != null)
            {
                model.timesheet.UserId = int.Parse(HttpContext.Session.GetString("UserId"));
                model.timesheet.MissionId = model.mission.MissionId;
                model.timesheet.CreatedAt = DateTime.Now;
                _db.Timesheets.Add(model.timesheet);
                _db.SaveChanges();
                return RedirectToAction("Timesheet", "Timesheet");
            }
            else
                return NotFound();
        }

       [HttpGet]
       public IActionResult Timegoaledit(int?id)
       {
           PlateformVM plateformVM = new PlateformVM();
           plateformVM.timesheet = _db.Timesheets.FirstOrDefault(x => x.TimesheetId == id);

            List<SelectListItem> list = new List<SelectListItem>();
           var temp = _db.MissionApplications.Where(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")) && x.DeletedAt == null && x.Mission.MissionType == 2).Select(x => x.MissionId).ToList();
           foreach (var item in temp)
           {
               var mission = _db.Missions.FirstOrDefault(x => x.MissionId == item);
               list.Add(new SelectListItem() { Text = mission.Title, Value = mission.MissionId.ToString() });
           }
           plateformVM.MissionGoalList = list;
           return View(plateformVM);
       }

        [HttpPost]
        public IActionResult Timegoaledit(PlateformVM model)
        {
            if (model.timesheet != null)
            {
                model.timesheet.UserId = int.Parse(HttpContext.Session.GetString("UserId"));
                model.timesheet.MissionId = model.mission.MissionId;
                model.timesheet.CreatedAt = DateTime.Now;
                _db.Timesheets.Add(model.timesheet);
                _db.SaveChanges();
                return RedirectToAction("Timesheet", "Timesheet");
            }
            else
                return NotFound();
        }
        public IActionResult timeGoalDelete(int? id)
        {
            var timesheet = _db.Timesheets.FirstOrDefault(x => x.TimesheetId == id);
            if (timesheet == null)
            {
                return NotFound();
            }
            timesheet.DeletedAt = DateTime.Now;
            _db.Timesheets.Remove(timesheet);
            _db.SaveChanges();
            return RedirectToAction("Timesheet", "Timesheet");
        }
        #endregion

    }
}

CI-Plateform project/CI-Plateform/Views/TimeSheet/Timegoaledit.cshtml
@using CI_Plateform.Models
@model PlateformVM

<div class="container-fluid" style="padding-left:0px;">
    <div class="row flex-nowrap container-fluid">
        <form class="pt-3" method="post" action="Timegoaledit" enctype="multipart/form-data">
            <input asp-for="timesheet.TimesheetId" hidden />
            <input asp-for="timesheet.Time" hidden />
            <input asp-for="timesheet.CreatedAt" hidden />

            <h5 style="margin:auto;width:50%;">Volunteering Hours</h5>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">

                <label for="" class="ps-0">Mission Title</label><br>
                <select id="ddlmissions" class="sherescontainer1" asp-for="timesheet.MissionId" asp-items="@Model.MissionGoalList" aria-label="Default select example" style="height: 30px;border: 1px solid #e0d8d8;color: #757575;">
                    <option class="sherescontainer1" selected>Select Mission</option>
                </select>
                <span asp-validation-for="timesheet.MissionId" class="text-danger"></span>
            </div>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">
                <label class="ps-0" asp-for="timesheet.Action">Action</label><br>
                <input asp-for="timesheet.Action" type="number" id="ab" name="timesheet.Action" class="sherescontainer1" required>
            </div>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">
                <label class="ps-0" asp-for="timesheet.DateVolunteered">Date</label><br>
                <input asp-for="timesheet.DateVolunteered" type="date" id="date" name="timesheet.DateVolunteered" class="sherescontainer1" required>
            </div>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">
                <label class="ps-0" asp-for="timesheet.Notes">Notes</label><br>
                <input asp-for="timesheet.Notes" type="text" id="m" name="timesheet.Notes" placeholder="Enter your note" class="sherescontainer1" required>
            </div>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">
                <label asp-for="timesheet.Status" class="ps-0" style="display:block;">Status</label>
                <select id="cmsStatus" asp-for="timesheet.Status" aria-label="Default select example" style="height: 30px;border: 1px solid #e0d8d8;color: #757575;">
                    <option class="sherescontainer1" selected>Open this select menu</option>
                    <option class="sherescontainer1" value="0">Not Active</option>
                    <option class="sherescontainer1" value="1">Active</option>
                </select>
            </div>
            <div class="row mt-2" style="float: right;margin:auto;width: 34%;">
                <button type="button" class="form-control rounded-pill btn btn-outline-dark font  sherescontainer10">
                    <a asp-controller="TimeSheet" asp-action="Timesheet" class="cancelbutton">
                        cancel
                    </a>
                </button>
                <button type="submit" asp-controller="TimeSheet" asp-action="Timegoaledit" class="form-control rounded-pill btn btn-outline-warning font"
                        style="width:auto;font-size: 12px;">
                    Save
                </button>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

CI-Plateform project/CI-Plateform/Views/TimeSheet/Timehouredit.cshtml
@using CI_Plateform.Models
@model PlateformVM

<div class="container-fluid" style="padding-left:0px;">
    <div class="row flex-nowrap container-fluid">
        <form class="pt-3" method="post" action="Timehouredit" enctype="multipart/form-data">
            <input asp-for="timesheet.TimesheetId" hidden/>
            <input asp-for="timesheet.Action" hidden/>
            <input asp-for="timesheet.CreatedAt" hidden/>
            
            <h5 style="margin:auto;width:50%;">Volunteering Hours</h5>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">

                <label for="" class="ps-0">Mission Title</label><br>
                <select id="ddlmissions" class="sherescontainer1" asp-for="timesheet.MissionId" asp-items="@Model.MissionHourList" aria-label="Default select example" style="height: 30px;border: 1px solid #e0d8d8;color: #757575;">
                    <option class="sherescontainer1" selected>Select Mission</option>
                </select>
                <span asp-validation-for="timesheet.MissionId" class="text-danger"></span>
            </div>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">
                <label class="ps-0" asp-for="timesheet.Time">Hours</label><br>
                <input asp-for="timesheet.Time" type="time" id="ab" name="timesheet.Time" class="sherescontainer1" required>
            </div>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">
                <label class="ps-0" asp-for="timesheet.DateVolunteered">Date</label><br>
                <input asp-for="timesheet.DateVolunteered" type="date" id="date" name="timesheet.DateVolunteered" class="sherescontainer1" required>
            </div>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">
                <label class="ps-0" asp-for="timesheet.Notes">Notes</label><br>
                <input asp-for="timesheet.Notes" type="text" id="m" name="timesheet.Notes" placeholder="Enter your note" class="sherescontainer1" required>
            </div>
            <div class="row mt-2" style="margin:auto;width:50%;font-size:10px;">
                <label asp-for="timesheet.Status" class="ps-0" style="display:block;">Status</label>
                <select id="cmsStatus" asp-for="timesheet.Status" aria-label="Default select example" style="height: 30px;border: 1px solid #e0d8d8;color: #757575;">
                    <option class="sherescontainer1" selected>Open this select menu</option>
                    <option class="sherescontainer1" value="0">Not Active</option>
                    <option class="sherescontainer1" value="1">Active</option>
                </select>
            </div>
            <div class="row mt-2" style="float: right;margin:auto;width: 34%;">
                <button type="button" class="form-control rounded-pill btn btn-outline-dark font  sherescontainer10">
                    <a asp-controller="TimeSheet" asp-action="Timesheet" class="cancelbutton">
                        cancel
                    </a>
                </button>
                <button type="submit" asp-controller="TimeSheet" asp-action="Timehouredit" class="form-control rounded-pill btn btn-outline-warning font"
                        style="width:auto;font-size: 12px;">
                    Save
                </button>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}