CI-Plateform project/CI-Plateform/Models/LoginViewModel.cs
using CI_Plateform.DbModels;
using DocumentFormat.OpenXml.Wordprocessing;
using System.ComponentModel.DataAnnotations;
using DataType = System.ComponentModel.DataAnnotations.DataType;

namespace CI_Plateform.Models
{
    public class LoginViewModel
    {
        public List<Banner> banner { get; set; }
        public User? User { get; set; } = null!;

        public string Email { get; set; } = null!;
        public string Token { get; set; } = null!;
        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 8)]
        [RegularExpression(@"^((?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()])).+$", ErrorMessage = "Password Must Contain 1-Symbol ,1-lowercase,1-Uppercase,1-digit")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; } = null!;
    }
}

CI-Plateform project/CI-Plateform/Controllers/PlateformController.cs
using CI_Plateform.DbModels;
using CI_Plateform.Models;
using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Wordprocessing;
using MailKit.Security;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using MimeKit.Text;
using MimeKit;
using System.Reflection;
using System.Runtime.Intrinsics.Arm;
using System.Text;
using MailKit.Net.Smtp;

namespace CI_Plateform.Controllers
{
    public class PlateformController : Controller
    {
        public ClPlatformContext _db = new ClPlatformContext();
        private readonly IWebHostEnvironment _hostEnvironment;

        public PlateformController(IWebHostEnvironment _environment)
        {
            _hostEnvironment = _environment;
        }

        #region Plateform(Home) Get
        [CheckSession]
        public IActionResult Plateform(int pg = 1)
        {
            PlateformVM plateformVM = new PlateformVM();
            plateformVM.Missions = _db.Missions.ToList();
            plateformVM.Timesheets = _db.Timesheets.ToList();

            plateformVM.user = _db.Users.FirstOrDefault(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")));

            List <SelectListItem> list1 = new List<SelectListItem>();
            var temp1 = _db.Skills.ToList();
            foreach (var item in temp1)
            {
                list1.Add(new SelectListItem() { Text = item.SkillName, Value = item.SkillId.ToString() });
            }
            plateformVM.SkillList = list1;

            List<SelectListItem> list2 = new List<SelectListItem>();
            var temp2 = _db.MissionThemes.ToList();
            foreach (var item in temp2)
            {
                list2.Add(new SelectListItem() { Text = item.Title, Value = item.MissionThemeId.ToString() });
            }
            plateformVM.ThemeList = list2;

            List<SelectListItem> list3 = new List<SelectListItem>();
            var temp3 = _db.Countries.ToList();
            foreach (var item in temp3)
            {
                list3.Add(new SelectListItem() { Text = item.Name, Value = item.CountryId.ToString() });
            }
            plateformVM.CountryList = list3;

            List<SelectListItem> list4 = new List<SelectListItem>();
            var temp4 = _db.Cities.ToList();
            foreach (var item in temp4)
            {
                list4.Add(new SelectListItem() { Text = item.Name, Value = item.CityId.ToString() });
            }
            plateformVM.CityList = list4;

            var cardData = new List<MissionCardModel>();

            var tempMission = _db.Missions.Where(x => x.DeletedAt == null).AsEnumerable().ToList();

            foreach (var item in tempMission)
            {
                cardData.Add(CreateCard(item));
            }
            /*plateformVM.missionsCard = cardData;*/
            /*return View(plateformVM);*/

            /*----------Pagenation--------------*/
            const int pageSize = 9;

            int recsCount = tempMission.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;

            var data = cardData.Skip(recSkip).Take(pager.PageSize).ToList();
            plateformVM.missionsCard = data;
            this.ViewBag.Pager = pager;
            return View(plateformVM);

            /*--------------------------*/
        }

        #endregion

        #region Plateform Filter
        [HttpPost]
        public PartialViewResult Filter(List<int>? CountryId, List<int>? CityId, List<int>? ThemeId, List<int>? SkillId, string? searchText, string? searchText2, int? sort, int pg = 1)
        {
            var cardData = new List<MissionCardModel>();
            var tempMission = new List<Mission>();

            #region Search
            if (searchText != null)
            {
                var missions = _db.Missions.Where(x => x.DeletedAt == null && x.Title.Contains(searchText)).AsEnumerable().ToList();
                foreach (var m in missions)
                {
                    bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                    if (t == false)
                    {
                        tempMission.Add(m);
                    }
                }
            }
            if (searchText2 != null)
            {
                var missions = _db.Missions.Where(x => x.DeletedAt == null && x.Title.Contains(searchText2)).AsEnumerable().ToList();
                foreach (var m in missions)
                {
                    bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                    if (t == false)
                    {
                        tempMission.Add(m);
                    }
                }
            }
            #endregion Search

            if (CountryId.Count != 0)
            {
                foreach (var n in CountryId)
                {
                    var missions = _db.Missions.Where(x => x.DeletedAt == null && x.CountryId == n).AsEnumerable().ToList();
                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }

            if (CityId.Count != 0)
            {
                foreach (var n in CityId)
                {
                    var missions = _db.Missions.Where(x => x.DeletedAt == null && x.CityId == n).AsEnumerable().ToList();
                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }

            if (ThemeId.Count != 0)
            {
                foreach (var n in ThemeId)
                {
                    var missions = _db.Missions.Where(x => x.DeletedAt == null && x.MissionThemeId == n).AsEnumerable().ToList();

                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }

            if (SkillId.Count != 0)
            {
                foreach (var n in SkillId)
                {
                    var missions = new List<Mission>();
                    var missionList = _db.MissionSkills.Where(x => x.SkillId == n).Select(m => m.MissionId).AsEnumerable().ToList();
                    foreach (var mission in missionList)
                    {
                        missions.Add(_db.Missions.FirstOrDefault(x => x.MissionId == mission));
                    }
                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }

            #region Default Mission
            if (CountryId.Count == 0 && CityId.Count == 0 && ThemeId.Count == 0 && SkillId.Count == 0 && searchText == null && searchText2 == null)
            {
                tempMission = _db.Missions.Where(x => x.DeletedAt == null).AsEnumerable().ToList();
            }
            #endregion Default Mission

            #region Create Card
            foreach (var item in tempMission)
            {
                cardData.Add(CreateCard(item));
            }
            #endregion Create Card

            #region Sort Data
            if (sort != null)
            {
                switch (sort)
                {
                    case 1:
                        cardData = cardData.OrderByDescending(x => x.mission.CreatedAt).ToList();
                        break;
                    case 2:
                        cardData = cardData.OrderBy(x => x.mission.CreatedAt).ToList();
                        break;
                    case 3:
                        cardData = cardData.OrderBy(x => x.seatsLeft).ToList();
                        break;
                    case 4:
                        cardData = cardData.OrderByDescending(x => x.seatsLeft).ToList();
                        break;
                    case 5:
                        cardData = cardData.OrderByDescending(x => x.favouriteMission).ToList();
                        break;
                    case 6:
                        cardData = cardData.OrderByDescending(x => x.mission.Deadline).ToList();
                        break;
                }
            }
            #endregion Sort Data


            PlateformVM plateformVM = new PlateformVM();
            const int pageSize = 9;

            int recsCount = tempMission.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;

            var data = cardData.Skip(recSkip).Take(pager.PageSize).ToList();
            plateformVM.missionsCard = data;
            this.ViewBag.Pager = pager;
            /*return View(plateformVM);*/

            return PartialView("_MissionGridPartial", data);
        }
        #endregion Mission Filter

        #region Favorite Mission
        [HttpPost]
        public IActionResult FavouriteMission(int id, int fav)
        {
            var UserId = Int64.Parse(HttpContext.Session.GetString("UserId"));
            if (fav == 1)
            {

CI-Plateform project/CI-Plateform/Views/Login/ForgotPasswordConfirmation.cshtml
<h4>
    If you have an account with us, we have sent an email
    with the instruction to reset your password.
</h4>

CI-Plateform project/CI-Plateform/Views/Login/Login.cshtml
@using CI_Plateform.Models
@model LoginViewModel

<script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
        crossorigin="anonymous"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

@if (TempData["Error"] != null)
{
    <script>
        toastr.error('@TempData["Error"]');
    </script>
}
@if (TempData["Done"] != null)
{
    <script>
        toastr.success('@TempData["Done"]');
    </script>
}

<div class="container container-fluid m-0 p-0">
    <div class="row">
        <div class="col-md-8 col-sm-12">
            @{
                var i = 0;
            }
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="true">
                <div class="carousel-indicators">
                    @foreach (var item in @Model.banner)
                    {
                        var tempclass = "";
                        @if (i == 0)
                        {
                            tempclass = "active";
                        }
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="@i"
                            class="@tempclass" aria-current="true" aria-label="Slide @i"
                            style="width: 5px;height: 5px;border-radius: 100%;"></button>
                        i++;
                    }
                </div>
                <div class="carousel-inner">
                    @{
                        i = 0;
                    }
                    @foreach (var item in @Model.banner)
                    {
                        var tempclass = "carousel-item";
                        @if (i == 0)
                        {
                            tempclass = "carousel-item active";
                            i++;
                        }
                        <div class="@tempclass">
                            <img src="@Url.Content(@item.Image)"
                             class="d-block w-100 imgheight" alt="Error">
                            <div class="carousel-caption d-none d-md-block">
                                <h3 class="CorouselTitle">
                                    @item.Title
                                </h3>
                                <p class="CorouselText">
                                    @item.Text
                                </p>
                            </div>
                        </div>
                    }
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="prev" style="display:none;">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                        data-bs-slide="next" style="display:none;">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>

            </div>
        </div>
        <div class="col-md-4 col-sm-12 wrapper vcenter-item" style="padding: 0px;">
            <div class="box">
                <form method="post">

                    <div class="form-group mb-3">
                        <label class="label font" asp-for="User.Email">Email Address</label>
                        <input type="email" class="form-control font" asp-for="User.Email"
                               style="display: inline;box-shadow: none;" placeholder="Email address">
                        <span asp-validation-for="User.Email" class="text-danger" style="font-size:12px;"></span>
                    </div>

                    <div class="form-group mb-3">
                        <label class="label font" asp-for="User.Password">Password</label>
                        <input type="password" class="form-control font" style="display: inline;box-shadow: none;"
                               asp-for="User.Password" placeholder="Password" required="">
                        <span asp-validation-for="User.Password" class="text-danger" style="font-size:12px;"></span>
                    </div>
                    <button type="submit" class="form-control rounded-pill btn btn-outline-warning font"
                            style="box-shadow:none;">
                        Login
                    </button>
                </form>
                <div class="font" style="text-align: center;">
                    <a asp-controller="Login" asp-action="LostPassword" class="hover">Lost your password?</a>
                    <br>Don't have account?
                    <a asp-controller="Login" asp-action="Register">Create an account</a>
                </div>
                <div class="font" style="text-align: center; padding-top: 30%;">
                    <a asp-controller="Login" asp-action="PolicyPage" class="hover">Privacy Policy</a>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
 <partial name = "_ValidationScriptsPartial"/>
}

CI-Plateform project/CI-Plateform/Views/Login/PolicyPage.cshtml
@using CI_Plateform.Models
@model UserVm

<div class="body-1">
    <div class="body-2">
        <div class="nevbar-1" style="height:43px;">
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid" style="padding:0px;justify-content: initial;">
                    <button class="navbar-toggler pad1 pe-2" type="button" data-bs-toggle="offcanvas"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="dropdown navbar-toggler border-0">
                        <a href="#" class="d-flex align-items-center text-black text-decoration-none"
                           id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="@Url.Content(Model.User.Avatar)" alt="hugenerd" width="30" height="30"
                                 class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu dropdown-menu-white text-small shadow">
                            <li><a class="dropdown-item" asp-controller="MyProfile" asp-action="Myprofile">My Profile</a></li>
                            <li><a class="dropdown-item" asp-controller="Timesheet" asp-action="Timesheet">Volunteering Timesheet</a></li>
                            <li><a class="dropdown-item" asp-controller="Login" asp-action="LogOut">Logout</a></li>
                        </ul>
                    </div>

                    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1"
                         id="navbarSupportedContent" aria-labelledby="offcanvasExampleLabel">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="offcanvasExampleLabel"></h5>
                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas"
                                    aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <div class="navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="hover2 nav-link" style="" asp-controller="StoryListing" asp-action="StoryListing">Stories </a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown"
                                           aria-expanded="false">
                                            Policy<i class="bi bi-chevron-down ps-1"
                                                     style="font-size:12px;"></i></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="Plateform" asp-action="Plateform">Volunteering</a></li>
                                            <li><a class="dropdown-item" href="#">Sponsored</a></li>
                                        </ul>
                                    </li>
                                </ul>

                                <div class="dropdown">
                                    <a href="#" class="d-flex align-items-center text-black text-decoration-none"
                                       id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                        <img src="@Url.Content(Model.User.Avatar)" alt="hugenerd" width="30" height="30"
                                             class="rounded-circle">
                                        <span class="d-none d-sm-inline mx-1">
                                            @Model.User.FirstName  <i class="bi bi-chevron-down ps-1" style="font-size:12px;"></i>
                                        </span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-white text-small shadow">
                                        <li><a class="dropdown-item" asp-controller="MyProfile" asp-action="Myprofile">My Profile</a></li>
                                        <li><a class="dropdown-item" asp-controller="Timesheet" asp-action="Timesheet">Volunteering Timesheet</a></li>
                                        <li><a class="dropdown-item" asp-controller="Login" asp-action="LogOut">Logout</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <hr>
    <div class="body-2">
        <h5>Privacy and Cookies Policy</h5>
        <div class="row">
            <div class="col-4" style="font-size:10px;">
                <div id="list-example" class="list-group" style="position: -webkit-sticky;position: sticky;top: 0;">
                    <a class="list-group-item list-group-item-action policycontainer1"
                       href="#list-item-1">
                        Introduction
                        <i class="bi bi-chevron-right float-end"></i>
                    </a>
                    <a class="list-group-item list-group-item-action policycontainer1" href="#list-item-2">
                        How does
                        use cookies?<i class="bi bi-chevron-right float-end"></i>
                    </a>
                    <a class="list-group-item list-group-item-action policycontainer1" href="#list-item-3">
                        How to
                        manage your cookie
                        preferences?<i class="bi bi-chevron-right float-end"></i>
                    </a>
                </div>
            </div>
            <div class="col-8">
                <div data-bs-spy="scroll" data-bs-target="#list-example" data-bs-smooth-scroll="true"
                     class="scrollspy-example" tabindex="0">

                    <h6 id="list-item-1">Introduction</h6>
                    <p style="font-size:10px;">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa
                        molestias
                        provident ut tempora
                        blanditiis voluptatem, amet inventore neque necessitatibus, cupiditate libero rerum.
                    </p>
                    <p style="font-size:10px;">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore vero
                        neque aperiam.
                    </p>
                    <p style="font-size:10px;">
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur
                        voluptate neque odit a officia
                        facilis velit animi, eius voluptatem incidunt harum asperiores perferendis iusto facere?
                    </p>
                    <hr>

                    <h6 id="list-item-2">How does use cookies?</h6>
                    <p style="font-size:10px;">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur
                        atque
                        dolor ea mollitia perferendis deleniti incidunt, ipsa ut tempore, fuga ipsum ipsam
                        voluptatem
                        deserunt iusto!
                    </p>
                    <h6 style="font-size:12px;">Why Optimy Uses These Technologies?</h6>
                    <p style="font-size:10px;">We use these technologies for a number of purposes, such as:</p>
                    <ul style="font-size:10px;">
                        <li>
                            But I must explain to you how all this mistaken idea of denouncing pleasure and praising
                            pain
                        </li>
                        <li>
                            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium
                            voluptatum deleniti atque
                        </li>
                        <li>
                            excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia
                            deserunt mollitia animi.
                        </li>
                        <li>
                            On the other hand, we denounce with righteous indignation and dislike men who are so
                            beguiled and demoralized
                        </li>
                        <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi id tempora pariatur.</li>
                    </ul>
                    <p style="font-size:10px;">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae
                        ipsum
                        nam sed, ducimus accusamus obcaecati voluptatibus nisi consequatur temporibus quasi eveniet
                        eum
                        similique quaerat
                        architecto assumenda? Inventore sapiente nulla quam nemo laudantium doloribus odio ratione,
                        consectetur est sunt facere itaque nam sequi possimus facilis eius voluptatibus dolorum
                        rerum
                        dicta, molestias nisi deleniti?
                    </p>
                    <hr>

                    <h6 id="list-item-3">How to manage your cookie preferences?</h6>
                    <p style="font-size:10px;">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates
                        quod
                        ipsam commodi nisi
                        eveniet deleniti, vel reiciendis culpa iure voluptatibus odit, laborum nam.
                    </p>
                    <p style="font-size:10px;">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum nemo
                        dignissimos tenetur culpa ad
                        aliquam sed delectus non blanditiis, architecto laboriosam similique dolorum nesciunt
                        corrupti
                        rerum iusto? Voluptatibus saepe optio beatae, perspiciatis itaque nisi iste veritatis
                        quisquam
                        libero. Totam, ipsum.
                    </p>
                    <h6 style="font-size:12px;">Subtitle goes here</h6>
                    <ol style="font-size:10px;">
                        <li>
                            But I must explain to you how all this mistaken idea of denouncing pleasure and praising
                            pain.
                            <ul>
                                <li>
                                    On the other hand, we denounce with righteous indignation and dislike men who
                                    are so
                                    beguiled.
                                </li>
                                <li>
                                    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
                                    praesentium voluptatum deleniti atque
                                </li>
                            </ul>
                        </li>
                        <li>
                            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium
                            voluptatum deleniti atque
                        </li>
                        <li>
                            On the other hand, we denounce with righteous indignation and dislike men who are so
                            beguiled and demoralized
                        </li>
                        <li>
                            But I must explain to you how all this mistaken idea of denouncing pleasure and praising
                            pain.
                        </li>
                        <li>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                            incididunt ut
                            labore et dolore
                        </li>
                    </ol>
                    <p style="font-size:10px;">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
                        aspernatur deleniti nulla. Nisi neque sunt modi temporibus, harum vero adipisci blanditiis
                        deleniti commodi ratione. Corrupti consequuntur qui fuga excepturi dicta placeat vel
                        officiis
                        ipsa.
                    </p>

                </div>
            </div>
        </div>
    </div>
    <hr style="margin-top:35px;">
    <div class="body-2">
        <a asp-controller="Login" asp-action="PolicyPage" class="hover">Privacy Policy</a>
    </div>
</div>