CI-Plateform project/CI-Plateform/Models/ShareStory.cs
using CI_Plateform.DbModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CI_Plateform.Models
{
    public class ShareStory
    {
        public Mission? mission { get; set; }
        public IEnumerable<SelectListItem> MissionList { get; set; }
        public StoryMedium? storyMedium { get; set; }
        public Story? Story { get; set; }
        public User? user { get; set; }
    }
}

CI-Plateform project/CI-Plateform/Controllers/StoryListingController.cs
using CI_Plateform.DbModels;
using CI_Plateform.Models;
using MailKit.Security;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using MimeKit.Text;
using MimeKit;
using MailKit.Net.Smtp;

namespace CI_Plateform.Controllers
{
    public class StoryListingController : Controller
    {
        public ClPlatformContext _db = new ClPlatformContext();
        private readonly IWebHostEnvironment _hostEnvironment;

        public StoryListingController(IWebHostEnvironment _environment)
        {
            _hostEnvironment = _environment;
        }

        #region StoryListing
        public IActionResult StoryListing(int pg = 1)
        {
            StoryListingVM storyListingVM = new StoryListingVM();
            storyListingVM.storys = _db.Stories.ToList();
            storyListingVM.user = _db.Users.FirstOrDefault(x => x.UserId == int.Parse(HttpContext.Session.GetString("UserId")));

            List<SelectListItem> list1 = new List<SelectListItem>();
            var temp1 = _db.Skills.ToList();
            foreach (var item in temp1)
            {
                list1.Add(new SelectListItem() { Text = item.SkillName, Value = item.SkillId.ToString() });
            }
            storyListingVM.SkillList = list1;

            List<SelectListItem> list2 = new List<SelectListItem>();
            var temp2 = _db.MissionThemes.ToList();
            foreach (var item in temp2)
            {
                list2.Add(new SelectListItem() { Text = item.Title, Value = item.MissionThemeId.ToString() });
            }
            storyListingVM.ThemeList = list2;

            List<SelectListItem> list3 = new List<SelectListItem>();
            var temp3 = _db.Countries.ToList();
            foreach (var item in temp3)
            {
                list3.Add(new SelectListItem() { Text = item.Name, Value = item.CountryId.ToString() });
            }
            storyListingVM.CountryList = list3;

            List<SelectListItem> list4 = new List<SelectListItem>();
            var temp4 = _db.Cities.ToList();
            foreach (var item in temp4)
            {
                list4.Add(new SelectListItem() { Text = item.Name, Value = item.CityId.ToString() });
            }
            storyListingVM.CityList = list4;

            var cardData = new List<StoryCardModel>();

            var tempMission = _db.Stories.Where(x => x.DeletedAt == null).AsEnumerable().ToList();

            foreach (var item in tempMission)
            {
                cardData.Add(StoryCard(item));
            }
            /*storyListingVM.storyCardModels = cardData;
            return View(storyListingVM);*/
            /*--------------------------*/
            const int pageSize = 9;
            int recsCount = tempMission.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;

            var data = cardData.Skip(recSkip).Take(pager.PageSize).ToList();
            storyListingVM.storyCardModels = data;
            this.ViewBag.Pager = pager;
            return View(storyListingVM);

            /*--------------------------*/
        }
        #endregion Story Detail

        #region StoryFilter
        [HttpPost]
        public PartialViewResult StoryFilter(List<int>? CountryId, List<int>? CityId, List<int>? ThemeId, List<int>? SkillId, string? searchText, string? searchText2, int pg = 1)
        {
            var cardData = new List<StoryCardModel>();
            var tempMission = new List<Story>();

            #region Search
            if (searchText != null)
            {
                var story = _db.Stories.Where(x => x.DeletedAt == null && x.Title.Contains(searchText)).AsEnumerable().ToList();
                foreach (var m in story)
                {
                    bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                    if (t == false)
                    {
                        tempMission.Add(m);
                    }
                }
            }
            if (searchText2 != null)
            {
                var story = _db.Stories.Where(x => x.DeletedAt == null && x.Title.Contains(searchText2)).AsEnumerable().ToList();
                foreach (var m in story)
                {
                    bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                    if (t == false)
                    {
                        tempMission.Add(m);
                    }
                }
            }
            #endregion Search

            if (CountryId.Count != 0)
            {
                foreach (var n in CountryId)
                {
                    var mission = _db.Missions.Where(x => x.DeletedAt == null && x.CountryId == n).AsEnumerable().ToList();
                    foreach (var p in mission)
                    {
                        var story = _db.Stories.Where(x => x.DeletedAt == null && x.MissionId == p.MissionId).AsEnumerable().ToList();
                        foreach (var m in story)
                        {
                            bool t = tempMission.Any(x => x.StoryId == m.StoryId);
                            if (t == false)
                            {
                                tempMission.Add(m);
                            }
                        }
                    }
                }
            }

            if (CityId.Count != 0)
            {
                foreach (var n in CityId)
                {
                    var mission = _db.Missions.Where(x => x.DeletedAt == null && x.CityId == n).AsEnumerable().ToList();
                    foreach (var p in mission)
                    {
                        var story = _db.Stories.Where(x => x.DeletedAt == null && x.MissionId == p.MissionId).AsEnumerable().ToList();
                        foreach (var m in story)
                        {
                            bool t = tempMission.Any(x => x.StoryId == m.StoryId);
                            if (t == false)
                            {
                                tempMission.Add(m);
                            }
                        }
                    }
                }
            }

            /*if (CityId.Count != 0)
            {
                foreach (var n in CityId)
                {
                    var story = _db.Stories.Where(x => x.DeletedAt == null && x.CityId == n).AsEnumerable().ToList();
                    foreach (var m in story)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }*/

            if (ThemeId.Count != 0)
            {
                foreach (var n in ThemeId)
                {
                    var mission = _db.Missions.Where(x => x.Deadline == null && x.MissionThemeId == n).AsEnumerable().ToList();
                    foreach (var p in mission)
                    {
                        var story = _db.Stories.Where(x => x.DeletedAt == null && x.MissionId == p.MissionId).AsEnumerable().ToList();

                        foreach (var m in story)
                        {
                            bool t = tempMission.Any(x => x.StoryId == m.StoryId);
                            if (t == false)
                            {
                                tempMission.Add(m);
                            }
                        }
                    }
                }
            }

            if (SkillId.Count != 0)
            {
                foreach (var n in SkillId)
                {
                    var missions = new List<Mission>();
                    var missionSkillList = _db.MissionSkills.Where(x => x.SkillId == n).AsEnumerable().ToList();
                    foreach (var p in missionSkillList)
                    {
                        var story = _db.Stories.Where(x => x.DeletedAt == null && x.MissionId == p.MissionId).AsEnumerable().ToList();

                        foreach (var m in story)
                        {
                            bool t = tempMission.Any(x => x.StoryId == m.StoryId);
                            if (t == false)
                            {
                                tempMission.Add(m);
                            }
                        }
                    }
                }
            }

            #region Default Mission
            if (CountryId.Count == 0 && CityId.Count == 0 && ThemeId.Count == 0 && SkillId.Count == 0 && searchText == null && searchText2 == null)
            {
                tempMission = _db.Stories.Where(x => x.DeletedAt == null).AsEnumerable().ToList();
            }
            #endregion Default Mission

            #region Create Card
            foreach (var item in tempMission)
            {
                cardData.Add(StoryCard(item));
            }
            #endregion Create Card

            StoryListingVM storyListingVM = new StoryListingVM();
            const int pageSize = 3;

            int recsCount = tempMission.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;

            var data = cardData.Skip(recSkip).Take(pager.PageSize).ToList();
            storyListingVM.storyCardModels = data;
            this.ViewBag.Pager = pager;

            return PartialView("_StoryGridPartial", data);
        }


        #endregion StoryFilter

        #region StoryCard
        public StoryCardModel StoryCard(Story item)
        {
            var card = new StoryCardModel();
            card.story = item;
            var img = _db.StoryMedia.FirstOrDefault(x => x.StoryId == item.StoryId);
            if (img == null)
            {
                card.CardImg = "~/assets/Animal-welfare-&-save-birds-campaign.png";

CI-Plateform project/CI-Plateform/Views/StoryListing/ShareStory.cshtml
@using CI_Plateform.Models
@model ShareStory

<script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
      $("#storyImg").change(function() {
        if (this.files && this.files[0]) {
          for (var i = 0; i < this.files.length; i++) {
            var reader = new FileReader();
            reader.onload = imageIsLoaded;
            reader.readAsDataURL(this.files[i]);
          }
        }
      });
    });
    function imageIsLoaded(e) {
        $('#imgDiv').append('<div style="position:relative;width: 92px;padding-left:0px;padding-bottom: 12px;"> <img src=' + e.target.result + ' data-mdb-img=' + e.target.result + ' alt="Gallery image 1" class="active w-100" /><div class="sherescontainer8">X</div> </div > ');
        };
    
</script>
@*<script>
    function myFunction() {
        const list = document.getElementById("imgDiv");
        list.removeChild(list.firstElementChild);
    }
</script>
*@
<div class="body-1">
    <div class="body-2">
        <div class="nevbar-1" style="height:43px;">
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid" style="padding:0px;justify-content:initial;">
                    <button class="navbar-toggler pad1" type="button" data-bs-toggle="offcanvas"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="dropdown navbar-toggler border-0">
                        <a href="#" class="d-flex align-items-center text-black text-decoration-none"
                           id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="@Url.Content(Model.user.Avatar)" alt="hugenerd" width="30" height="30"
                                 class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu dropdown-menu-white text-small shadow">
                            <li><a class="dropdown-item" asp-controller="MyProfile" asp-action="Myprofile">My Profile</a></li>
                            <li><a class="dropdown-item" asp-controller="Timesheet" asp-action="Timesheet">Volunteering Timesheet</a></li>
                            <li><a class="dropdown-item" asp-controller="Login" asp-action="LogOut">Logout</a></li>
                        </ul>
                    </div>
                    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1"
                         id="navbarSupportedContent" aria-labelledby="offcanvasExampleLabel">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="offcanvasExampleLabel"></h5>
                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas"
                                    aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <div class="navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="hover2 nav-link" style="" asp-controller="StoryListing" asp-action="StoryListing">Stories </a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown"
                                           aria-expanded="false">
                                            Policy <i class="bi bi-chevron-down ps-1" style="font-size:12px;"></i>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="Plateform" asp-action="Plateform">Volunteering</a></li>
                                            <li><a class="dropdown-item" href="#">Sponsored</a></li>
                                        </ul>
                                    </li>
                                </ul>

                                <div class="dropdown">
                                    <a href="#" class="d-flex align-items-center text-black text-decoration-none"
                                       id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                        <img src="@Url.Content(Model.user.Avatar)" alt="hugenerd" width="30" height="30"
                                             class="rounded-circle">
                                        <span class="d-none d-sm-inline mx-1">
                                            @Model.user.FirstName <i class="bi bi-chevron-down ps-1" style="font-size:12px;"></i>
                                        </span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-white text-small shadow">
                                        <li><a class="dropdown-item" asp-controller="MyProfile" asp-action="Myprofile">My Profile</a></li>
                                        <li><a class="dropdown-item" asp-controller="Timesheet" asp-action="Timesheet">Volunteering Timesheet</a></li>
                                        <li><a class="dropdown-item" asp-controller="Login" asp-action="LogOut">Logout</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <hr>
    <div class="body-2">
        <h3>Share your story</h3>
        <form class="pt-3" method="post" action="ShareStory" enctype="multipart/form-data">
            <div class="row" style="margin:18px 0px;">
                <div class="col-md-4 col-sm-12 mt-2" style="padding:0px 15px 0px 0px;">
                    <label for="">Select Mission</label><br>
                    <select id="ddlmissions" class="sherescontainer1" asp-for="Story.MissionId" asp-items="@Model.MissionList" aria-label="Default select example">
                        <option class="sherescontainer1" selected>Select Mission</option>
                    </select>
                    <span asp-validation-for="Story.MissionId" class="text-danger"></span>
                </div>
                <div class="col-md-4 col-sm-12 mt-2" style="padding:0px 15px 0px 0px;">
                    <label asp-for="Story.Title">My Story Title</label><br>
                    <input asp-for="Story.Title" type="text" id="name" name="Story.Title" placeholder="Enter story title" class="sherescontainer1">
                </div>
                <div class="col-md-4 col-sm-12 mt-2" style="padding:0px 15px 0px 0px;">
                    <label asp-for="Story.PublishedAt">Date</label><br>
                    <input asp-for="Story.PublishedAt" type="date" id="date" name="Story.PublishedAt" class="sherescontainer1">
                </div>

                <div class="row" style="margin:18px 0px;padding-left: 0px;">
                    <label asp-for="Story.Description" style="padding:0px;">Why i volunteer??</label><br>
                    <textarea asp-for="Story.Description" name="Story.Description" placeholder="Enter description..." style="color: #757575;width:100%;height:100px;resize:none;border: 1px solid #d9d9d9;"></textarea>
                </div>

                <div class="row" style="margin:18px 0px;padding-left: 0px;">
                    <label for="url" style="padding:0px;">Enter Video URL</label><br>
                    <input type="text" id="url" name="url" placeholder="Enter your url">
                </div>
                <div class="row" style="margin:18px 0px;padding-left: 0px;">
                    <label for="uploadpic" style="padding:0px;">Upload Story photos</label><br>
                    <div class="sherescontainer5">
                        <div class="sherescontainer6">
                            <div>
                                <input class="form-control form-control-sm mb-2" id="storyImg" type="file" style="width: auto;
                                font-size: xx-small;margin-left: auto;margin-right: auto;" multiple name="storyMedia">
                            </div>
                            <p style="font-size:8px; color: #757575;">Drag and Drop Picture and Video hear</p>
                        </div>
                    </div>
                </div>
                @*<button onclick="myFunction()" style="width:auto;border:1px solid;font-size:12px;">Remove</button>*@
                <div class="row" style="margin:18px 0px; display: flex;padding-left: 0px;" id="imgDiv">
                    @*<div class="sherescontainer7">
                        <img src="~/assets/img11.png" alt="Error" style="width:75px; height:75px;">
                        <button class="sherescontainer8">
                            <img src="~/assets/cancel.png" alt="Error"
                                 class="sherescontainer9">
                        </button>
                    </div>
                    <div style="position:relative;width: auto;padding-left:0px;padding-bottom: 12px;">
                        <img src="~/assets/CSR-initiative-stands-for-Coffee--and-Farmer-Equity.png" alt="Error"
                             style="width:75px; height:75px;">
                        <button class="sherescontainer8">
                            <img src="~/assets/cancel.png" alt="Error"
                                 class="sherescontainer9">
                        </button>
                    </div>*@
                </div>
                <div class="row" style="margin:18px 0px;display:block;padding-left: 0px;">
                    <button type="submit" asp-controller="StoryListing" asp-action="StoryListing"
                            class="form-control rounded-pill btn btn-outline-secondary font  sherescontainer10">
                        Cancle
                    </button>
                    <button type="submit" asp-controller="StoryListing" asp-action="ShareStory"
                            class="form-control rounded-pill btn btn-outline-warning font sherescontainer11 ms-2">
                        Submit
                    </button>
                    @*<button type="submit"
                    class="form-control rounded-pill btn btn-outline-warning font sherescontainer11">
                    Save
                    </button>*@
                </div>
            </div>
        </form>
    </div>
    <hr style="margin-top:35px;">
    <div class="body-2">
        <a asp-controller="Login" asp-action="PolicyPage" class="hover">Privacy Policy</a>
    </div>
</div>

CI-Plateform project/CI-Plateform/Views/StoryListing/_CoWorkerPartial.cshtml
@using CI_Plateform.DbModels
@model Story

<div class="modal fade" id="SuggestWorker">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="modalForm" method="post" action="SuggestCoWorker">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Suggest Co-Worker</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <input asp-for="StoryId" hidden />
                        <div class="col-12 mt-3">
                            <label>Email</label>
                            <input type="text" class="form-control" name="WorkerEmail" required="" placeholder="Enter Email" id="" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary rounded-pill"
                            data-bs-dismiss="modal">
                        Cancel
                    </button>
                    <button type="submit" class="btn btn-outline-warning rounded-pill">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>

CI-Plateform project/CI-Plateform/Views/StoryListing/_StoryGridPartial.cshtml
@using CI_Plateform.Models;
@model List<StoryCardModel>

<script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
        crossorigin="anonymous"></script>




<div class="row">
    @foreach (var card in @Model)
    {
        <div class="col-md-4 col-sm-12 imghover" style="padding: 0px 20px 12px 4px; margin-top:12px;">
            <div class="card h-100 shadow">
                <div class="cardcontainer11">
                    @*<img src="~/assets/Grow-Trees-On-the-path-to-environment-sustainability.png"
                     class="card-img-top" alt="Error">*@
                    <img src="@Url.Content(@card.CardImg)" class="card-img-top" alt="Error" style="height: 161px;">
                    <div class="listcontaier5">
                        <div class="card-body" style="text-align:center;padding:18%;">
                            <button class="listcontainer3" type="button" onclick="return location.href=' @Url.Action("StoryDetail","StoryListing",new {id=@card.story.StoryId}) '">
                                View details
                                <i class="bi bi-arrow-right"></i>
                            </button>
                        </div>
                    </div>
                    <button class="cardcontainer15">
                        @card.theme
                    </button>
                </div>
                <div class="card-body" style="margin-bottom:-15px;position: relative;">
                    <h4 style="font-size:15px;">@card.story.Title</h4>
                    <p style="font-size:12px;">
                        @card.story.Description
                    </p>
                </div>
                
                <div class="card-body" style="display: flex;">
                    <img class="listcontainer4" src="@Url.Content(card.Userimg)" alt="Error">
                    <p style="font-size: 11px;padding-top: 12px;margin-left:6px;">@card.user.FirstName</p>
                </div>
                
            </div>
        </div>
    }
    
</div>